---
- name: Ansible Playbook to setup Ubuntu system
  hosts: local_system
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
  roles:
    - { role: git, become: yes, tags: ["git"] }
    - { role: dotstrap.fish, become: yes, tags: ["cli", "fish"] }
    - { role: terminal, tags: ["terminal"] }
    - { role: andrewrothstein.starship, tags: ["cli", "starship"] }
    - {
        role: hussainweb.chezmoi,
        become: yes,
        chezmoi_init_url: "gazab",
        tags: ["cli", "chezmoi"],
      }
    - role: drew-kun.nerdfonts
      vars:
        - nerdfonts_fonts:
            - fontname: "JetBrainsMono"
              name: "font-jetbrains-mono"
            - fontname: "Terminus"
              name: "font-terminess-ttf-nerd-font"
            - fontname: "NerdFontsSymbolsOnly"
      tags:
        - "fonts"
    - { role: fonts, become: yes, tags: ["fonts"] }
    - { role: common, become: yes, tags: ["common"] }
    - { role: communication, become: yes, tags: ["communication"] }
    - { role: development, become: yes, tags: ["development"] }
    - { role: multimedia, become: yes, tags: ["multimedia"] }
    - { role: python, become: yes, tags: ["python"] }
    - { role: kubernetes, become: yes, tags: ["kubernetes"] }
    - { role: terraform, become: yes, tags: ["terraform"] }
    - { role: tools, become: yes, tags: ["tools"] }
  tasks:
    - debug: msg="You are the user {{ lookup('env','USER') }}"
