- name: Install pip for python 3
  tags: cli
  apt:
    pkg:
      - python3-pip
      - python3-dev
    state: latest
    update_cache: yes

- name: Install python-is-python3 (symlinks /usr/bin/python to python3)
  tags: cli
  apt:
    pkg: python-is-python3
    state: latest

- name: Install github3.py
  ansible.builtin.pip:
    name: github3.py
