- name: Set login shell of user {{ ansible_env.USER }} to `/usr/bin/fish` with `usermod`
  tags: cli
  ansible.builtin.command: usermod --shell /usr/bin/fish {{ ansible_env.USER }}
  become: true
  changed_when: false

- name: get oh-my-fish repo
  tags: cli
  git:
    repo: "https://github.com/oh-my-fish/oh-my-fish.git"
    dest: ~/.local/share/git/oh-my-fish

- name: install oh-my-fish
  tags: cli
  shell:
    cmd: "bin/install --offline --noninteractive --yes"
    executable: /usr/bin/fish
    chdir: ~/.local/share/git/oh-my-fish

- name: Install/update kitty terminal emulator
  shell: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin launch=n

- name: Desktop icon for kitty
  shell: |
    mkdir ~/.local/bin/
    ln -s ~/.local/kitty.app/bin/kitty ~/.local/bin/
    # Place the kitty.desktop file somewhere it can be found by the OS
    cp ~/.local/kitty.app/share/applications/kitty.desktop ~/.local/share/applications/
    # If you want to open text files and images in kitty via your file manager also add the kitty-open.desktop file
    cp ~/.local/kitty.app/share/applications/kitty-open.desktop ~/.local/share/applications/
    # Update the paths to the kitty and its icon in the kitty.desktop file(s)
    sed -i "s|Icon=kitty|Icon=/home/$USER/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" ~/.local/share/applications/kitty*.desktop
    sed -i "s|Exec=kitty|Exec=/home/$USER/.local/kitty.app/bin/kitty|g" ~/.local/share/applications/kitty*.desktop
